// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfjbeqkiaxzpegtwtgbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmamJlcWtpYXh6cGVndHd0Z2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTI5NzEsImV4cCI6MjA2NDU2ODk3MX0.s1VYUpiFRotgLlWwjtJmn4e-DH3UijFbn1lAgYWWI-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);